# tomcat
server:
  port: 8003
spring:
  application:
    name: coisini-backup-server
  boot:
    admin:
      client:
        url: "http://localhost:8761"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# 注册到consul的服务名称
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# backup datasource
coisini:
  backup:
    datasource:
      host: localhost
      userName: root
      password: sunday
      database: coisini